### ISSUE TITLE
Create Button Component

### ISSUE THREAD

**Issue by cremirdevio** [cremirdevio/qwikbill#1]
You are to create a button component for reuse throughout the whole project.

In the `components` folder, create a folder named `ui`, then create the `Button` component inside this folder. Every small component like Button, Text, etc will be inside the `components/ui` folder, while other components will be stored inside the `components` folder directly.

The button will have a width of 100% by default.
The following props are required for the button: variant & className
- variant: the values can either be `solid` or `outline`
- colorScheme: can be `primary`, `danger`

Be sure to ask any question at all.

**Comment by aishwarya-mali** [comment]
@cremirdevio I'd like to work on this issue.

**Comment by cremirdevio** [comment]
> @cremirdevio I'd like to work on this issue.

@aishwarya-mali  Its been assigned to someone else, would you be willing to work on another issue?

**Comment by aishwarya-mali** [comment]
> would you be willing to work on another issue?

Sure. Is it [this](https://github.com/cremirdevio/qwikbill/issues/2) one?

**Comment by cremirdevio** [comment]
@aishwarya-mali Great one!

I asked because this project is actually a project to help beginners get experience working with a real web application and also learn how to collaborate with other developers. Three years feels like an intermediate already.
